meta_product_name: "Belay Buddies"
meta_title: "Belay Buddies - Find a climbing partner that fits around your busy schedule."
meta_description: "Belay Buddies is a way for new and experienced climbers to find climbing partners based around their busy schedules."
meta_image: "stronghold_2.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
